<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
     <head>
          <title>The Sarah Varon Foundation</title>
          <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
          <meta http-equiv="Content-Language" content="en"/>
          <link rel="stylesheet" type="text/css" href="style.css" />
     </head>
     <body>
          <div id="frame"> 
               <div id="header">
                    <div class="headContent">
                         <img src="images/headerLt.jpg" width="140" height="140" alt="Sarah and her family" /><br />Sarah &amp; Family
                    </div>
                    <div class="headContent">
                         <img class="pad" src="images/logo.gif" width="417" height="112" alt="The Sarah Varon Foundation - The race to find a cure for Retts Syndrome" />
                    </div>
                    <div class="headContent">
                         <img src="images/headerRt.jpg" width="140" height="140" alt="Sarah and her family" /><br />Sarah &amp; Family
                    </div>
                    <br class="clearLt" />
               </div>
               <div>
                    <marquee scrolldelay="0" scrollamount="7">NEWS FLASH &lt;&lt; Recent studies completely reverse Rett Syndrome in mice. (view "Announcements") &gt;&gt; Please click "Donations" to help Rett research find the cure.</marquee>
               </div>

