<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
   <head>
      <title>The Sarah Varon Foundation for Rett Syndrome Research</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta http-equiv="Content-Language" content="en">
      <link rel="stylesheet" type="text/css" href="style.css">
   </head>
   <body onload="init();">
      <div id="frame"> 
         <div>
            <p align="center">
               <img src="images/headerLt.jpg" width="140" height="140" alt="Sarah and Alex at Baker Beach">
               <h1>The Sarah Varon Foundation</h1>
               <hr>
               <h2>The race to find a cure for Retts Syndrome</h2>
               <img src="images/headerRt.jpg" width="140" height="140" alt="Sarah and Dad at Baker Beach">
            </p>
         </div>
