<?php
$pgId = "phot";
require_once( 'headerInc.php' );
require_once( 'navInc.php' );
?>
         <div id="mainContent">
            <div id="gallery">
               <div id="sarah">
                  <h4><span>Sarah  |  </span><a href="#gallery" onclick="swapGalleries('family');">Family</a></h4>
                  <div>
                     <img id="sarah_shot" src="images/gallery/sarah/99944.jpg" alt="Sarah getting a Christmas tree" height="300" width="440">
                  </div>
                  <div id="sarah_cap"><span>Sarah getting a Christmas tree</span></div>
                  <div class="thumbs">
                     <a onclick="updateImg('images/gallery/sarah/99944.jpg','sarah_','440','300','Sarah getting a Christmas tree');" href="#gallery"><img alt="Sarah getting a Christmas tree" src="images/gallery/sarahThumbs/99944t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99945.jpg','sarah_','440','300','Sarah and Lilly using Sarah\'s computer - Thanksgiving');" href="#gallery"><img alt="Sarah and Lilly using Sarah's computer - Thanksgiving" src="images/gallery/sarahThumbs/99945t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99946.jpg','sarah_','440','300','Sarah and her cousin Dan - Thanksgiving');" href="#gallery"><img alt="Sarah and her cousin Dan - Thanksgiving" src="images/gallery/sarahThumbs/99946t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99947.jpg','sarah_','440','300','Sarah');" href="#gallery"><img alt="Sarah" src="images/gallery/sarahThumbs/99947t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99948.jpg','sarah_','440','300','Sarah');" href="#gallery"><img alt="Sarah" src="images/gallery/sarahThumbs/99948t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99949.jpg','sarah_','440','300','Sarah - Halloween');" href="#gallery"><img alt="Sarah - Halloween" src="images/gallery/sarahThumbs/99949t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99950.jpg','sarah_','400','600','Sarah and her dad');" href="#gallery"><img alt="Sarah and her dad" src="images/gallery/sarahThumbs/99950t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99951.jpg','sarah_','440','300','Sarah in shades');" href="#gallery"><img alt="Sarah in shades" src="images/gallery/sarahThumbs/99951t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99952.jpg','sarah_','440','300','Birthday Girl');" href="#gallery"><img alt="Birthday Girl" src="images/gallery/sarahThumbs/99952t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99953.jpg','sarah_','440','300','4th of July at Lake of the Pines');" href="#gallery"><img alt="4th of July at Lake of the Pines" src="images/gallery/sarahThumbs/99953t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99954.jpg','sarah_','440','300','Halloween');" href="#gallery"><img alt="Halloween" src="images/gallery/sarahThumbs/99954t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99957.jpg','sarah_','400','600','2nd grade school photo');" href="#gallery"><img alt="2nd grade school photo" src="images/gallery/sarahThumbs/99957t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99958.jpg','sarah_','440','300','at the swimming pool');" href="#gallery"><img alt="at the swimming pool" src="images/gallery/sarahThumbs/99958t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99959.jpg','sarah_','440','300','Sarah');" href="#gallery"><img alt="Sarah" src="images/gallery/sarahThumbs/99959t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99960.jpg','sarah_','400','600','Dad and Sarah at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Dad and Sarah at Baker Beach - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99960t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99961.jpg','sarah_','400','600','Dad and Sarah at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Dad and Sarah at Baker Beach - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99961t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99962.jpg','sarah_','440','300','Alexandra and Sarah at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Alexandra and Sarah at Baker Beach - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99962t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99963.jpg','sarah_','440','300','Sarah and her friend at the Discovery Museum');" href="#gallery"><img alt="Sarah and her friend at the Discovery Museum" src="images/gallery/sarahThumbs/99963t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99964.jpg','sarah_','440','300','Sarah and Annie at the Discovery Museum');" href="#gallery"><img alt="Sarah and Annie at the Discovery Museum" src="images/gallery/sarahThumbs/99964t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99965.jpg','sarah_','440','300','Sarah and her friends on their way to the Discovery Museum');" href="#gallery"><img alt="Sarah and her friends on their way to the Discovery Museum" src="images/gallery/sarahThumbs/99965t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99966.jpg','sarah_','440','300','The three girls in Sarah\'s bed');" href="#gallery"><img alt="The three girls in Sarah's bed" src="images/gallery/sarahThumbs/99966t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99967.jpg','sarah_','440','300','Sarah\'s 5th birthday');" href="#gallery"><img alt="Sarah's 5th birthday" src="images/gallery/sarahThumbs/99967t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99968.jpg','sarah_','440','300','Our little butterfly');" href="#gallery"><img alt="Our little butterfly" src="images/gallery/sarahThumbs/99968t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99969.jpg','sarah_','440','300','The three girls');" href="#gallery"><img alt="The three girls" src="images/gallery/sarahThumbs/99969t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99970.jpg','sarah_','440','300','Sarah Seltsam, Sarah and Alexandra');" href="#gallery"><img alt="Sarah Seltsam, Sarah and Alexandra" src="images/gallery/sarahThumbs/99970t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99971.jpg','sarah_','440','300','Sarah\'s 5th birthday');" href="#gallery"><img alt="Sarah's 5th birthday" src="images/gallery/sarahThumbs/99971t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99972.JPG','sarah_','440','300','Sarah\'s 5th birthday');" href="#gallery"><img alt="Sarah's 5th birthday" src="images/gallery/sarahThumbs/99972t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99973.jpg','sarah_','440','300','Sarah - Christmas');" href="#gallery"><img alt="Sarah - Christmas" src="images/gallery/sarahThumbs/99973t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99974.jpg','sarah_','440','300','Sarah, Alexandra and Lilly - Photo by Leslie Corrado');" href="#gallery"><img alt="Sarah, Alexandra and Lilly - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99974t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99975.jpg','sarah_','400','600','Sarah - Photo by Leslie Corrado');" href="#gallery"><img alt="Sarah - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99975t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99976.jpg','sarah_','400','600','Sarah - Photo by Leslie Corrado');" href="#gallery"><img alt="Sarah - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99976t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99977.jpg','sarah_','400','600','Sarah - Photo by Leslie Corrado');" href="#gallery"><img alt="Sarah - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99977t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99978.jpg','sarah_','400','600','Sarah - Photo by Leslie Corrado');" href="#gallery"><img alt="Sarah - Photo by Leslie Corrado" src="images/gallery/sarahThumbs/99978t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99979.jpg','sarah_','400','600','Sarah and Alexandra - Halloween');" href="#gallery"><img alt="Sarah and Alexandra - Halloween" src="images/gallery/sarahThumbs/99979t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99980.jpg','sarah_','440','300','Dad, Sarah and Lilly - Halloween');" href="#gallery"><img alt="Dad, Sarah and Lilly - Halloween" src="images/gallery/sarahThumbs/99980t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99981.jpg','sarah_','440','300','Alexandra and Sarah');" href="#gallery"><img alt="Alexandra and Sarah" src="images/gallery/sarahThumbs/99981t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99982.jpg','sarah_','400','600','Sarah and Lilly');" href="#gallery"><img alt="Sarah and Lilly" src="images/gallery/sarahThumbs/99982t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99983.jpg','sarah_','400','600','The three girls');" href="#gallery"><img alt="The three girls" src="images/gallery/sarahThumbs/99983t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99984.jpg','sarah_','440','300','Sarah and Lilly');" href="#gallery"><img alt="Sarah and Lilly" src="images/gallery/sarahThumbs/99984t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99985.jpg','sarah_','400','600','The three girls');" href="#gallery"><img alt="The three girls" src="images/gallery/sarahThumbs/99985t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99986.jpg','sarah_','440','300','Mom, Sarah and Lilly');" href="#gallery"><img alt="Mom, Sarah and Lilly" src="images/gallery/sarahThumbs/99986t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99987.jpg','sarah_','400','600','Sarah walking at school');" href="#gallery"><img alt="Sarah walking at school" src="images/gallery/sarahThumbs/99987t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99988.jpg','sarah_','440','300','Sarah and Lisa (Sarah\'s Physical Therapist)');" href="#gallery"><img alt="Sarah and Lisa (Sarah's Physical Therapist)" src="images/gallery/sarahThumbs/99988t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99989.jpg','sarah_','400','600','Mom and Sarah on Sarah\'s 4th birthday');" href="#gallery"><img alt="Mom and Sarah on Sarah's 4th birthday" src="images/gallery/sarahThumbs/99989t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99990.jpg','sarah_','400','600','Sarah, Grandma and Mom on Sarah\'s 4th birthday');" href="#gallery"><img alt="Sarah, Grandma and Mom on Sarah's 4th birthday" src="images/gallery/sarahThumbs/99990t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99991.jpg','sarah_','440','300','Sarah\'s 4th birthday party at school');" href="#gallery"><img alt="Sarah's 4th birthday party at school" src="images/gallery/sarahThumbs/99991t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99992.jpg','sarah_','440','300','Sarah\'s 4th birthday party at school');" href="#gallery"><img alt="Sarah's 4th birthday party at school" src="images/gallery/sarahThumbs/99992t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99993.jpg','sarah_','400','600','Sarah\'s 4th birthday party at school');" href="#gallery"><img alt="Sarah's 4th birthday party at school" src="images/gallery/sarahThumbs/99993t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99994.jpg','sarah_','440','300','Sarah\'s 4th birthday');" href="#gallery"><img alt="Sarah's 4th birthday" src="images/gallery/sarahThumbs/99994t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99995.jpg','sarah_','440','300','Sarah and Aunt Jenny on Sarah\'s 4th birthday');" href="#gallery"><img alt="Sarah and Aunt Jenny on Sarah's 4th birthday" src="images/gallery/sarahThumbs/99995t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99996.jpg','sarah_','440','300','Sarah at Easter');" href="#gallery"><img alt="Sarah at Easter" src="images/gallery/sarahThumbs/99996t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99997.jpg','sarah_','400','600','Sarah\'s fist day of school');" href="#gallery"><img alt="Sarah's fist day of school" src="images/gallery/sarahThumbs/99997t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/sarah/99998.jpg','sarah_','440','300','Dad and Sarah at Disneyland');" href="#gallery"><img alt="Dad and Sarah at Disneyland" src="images/gallery/sarahThumbs/99998t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/sarah/99999.jpg','sarah_','1','1','');" href="#gallery"><img alt="" src="images/gallery/sarahThumbs/99999t.jpg" height="1" width="1"></a></div>
               </div>
               <div id="family" style="display:none;">
                  <h4><a href="#gallery" onclick="swapGalleries('sarah');">Sarah</a><span>  |  Family</span></h4>
                  <div>
                     <img id="family_shot" src="images/gallery/family/99937.jpg" alt="The Varon Girls getting a Christmas Tree" height="300" width="440">
                  </div>
                  <div id="family_cap"><span>The Varon Girls getting a Christmas Tree</span></div>
                  <div class="thumbs">
                     <a onclick="updateImg('images/gallery/family/99937.jpg','family_','440','300','The Varon Girls getting a Christmas Tree');" href="#gallery"><img alt="The Varon Girls getting a Christmas Tree" src="images/gallery/familyThumbs/99937t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99938.jpg','family_','400','600','Mom, Sarah and Grandma in front of the Museum of Modern Art');" href="#gallery"><img alt="Mom, Sarah and Grandma in front of the Museum of Modern Art" src="images/gallery/familyThumbs/99938t.jpg" height="40" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99939.jpg','family_','440','300','Mom, Aunt Jenny, cousins and sisters outside the Velveteen Rabbit');" href="#gallery"><img alt="Mom, Aunt Jenny, cousins and sisters outside the Velveteen Rabbit" src="images/gallery/familyThumbs/99939t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99940.jpg','family_','440','300','Sarah\'s cousin Maggie and Aunt Jenny - 4th of July at Lake of the Pines');" href="#gallery"><img alt="Sarah's cousin Maggie and Aunt Jenny - 4th of July at Lake of the Pines" src="images/gallery/familyThumbs/99940t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99941.jpg','family_','440','300','Sarah\'s Grandpa and cousin John - 4th of July at Lake of the Pines');" href="#gallery"><img alt="Sarah's Grandpa and cousin John - 4th of July at Lake of the Pines" src="images/gallery/familyThumbs/99941t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99942.jpg','family_','440','300','Lindsay and Lilly - 4th of July at Lake of the Pines');" href="#gallery"><img alt="Lindsay and Lilly - 4th of July at Lake of the Pines" src="images/gallery/familyThumbs/99942t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99943.jpg','family_','440','300','Alix, Sarah and Lilly at The Velveteen Rabbit')" href="#gallery"><img alt="Alix, Sarah and Lilly at The Velveteen Rabbit" src="images/gallery/familyThumbs/99943t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99944.jpg','family_','440','300','Sarah and Alix at The Velveteen Rabbit');" href="#gallery"><img alt="Sarah and Alix at The Velveteen Rabbit" src="images/gallery/familyThumbs/99944t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99945.jpg','family_','440','300','Lilly, Sarah and Alix - Halloween');" href="#gallery"><img alt="Lilly, Sarah and Alix - Halloween" src="images/gallery/familyThumbs/99945t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99946.jpg','family_','400','600','Sarah with her sisters and grandmothers');" href="#gallery"><img alt="Sarah with her sisters and grandmothers" src="images/gallery/familyThumbs/99946t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99947.jpg','family_','440','300','Sarah and Mom on carousel');" href="#gallery"><img alt="Sarah and Mom on carousel" src="images/gallery/familyThumbs/99947t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99948.jpg','family_','440','300','Sarah\'s parents on their 10th wedding anniversary');" href="#gallery"><img alt="Sarah's parents on their 10th wedding anniversary" src="images/gallery/familyThumbs/99948t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99949.jpg','family_','440','300','Sarah\'s parents on their 10th wedding anniversary');" href="#gallery"><img alt="Sarah's parents on their 10th wedding anniversary" src="images/gallery/familyThumbs/99949t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99950.jpg','family_','440','300','Sarah\'s parents on their 10th wedding anniversary');" href="#gallery"><img alt="Sarah's parents on their 10th wedding anniversary" src="images/gallery/familyThumbs/99950t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99951.jpg','family_','400','600','Dad, Sarah and Alix');" href="#gallery"><img alt="Dad, Sarah and Alix" src="images/gallery/familyThumbs/99951t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99952.jpg','family_','400','600','The Varon Family');" href="#gallery"><img alt="The Varon Family" src="images/gallery/familyThumbs/99952.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99953.jpg','family_','440','300','Sarah and her mom');" href="#gallery"><img alt="Sarah and her mom" src="images/gallery/familyThumbs/99953t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99954.jpg','family_','440','300','Sarah with Aunt Jenny');" href="#gallery"><img alt="Sarah with Aunt Jenny" src="images/gallery/familyThumbs/99954t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99955.jpg','family_','440','300','Lindsay, Sarah and Lilly');" href="#gallery"><img alt="Lindsay, Sarah and Lilly" src="images/gallery/familyThumbs/99955t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99956.jpg','family_','440','300','Alix, Sarah and Lilly');" href="#gallery"><img alt="Alix, Sarah and Lilly" src="images/gallery/familyThumbs/99956t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99957.jpg','family_','440','300','Sarah with her mom and dad');" href="#gallery"><img alt="Sarah with her mom and dad" src="images/gallery/familyThumbs/99957t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99958.jpg','family_','440','300','Sarah with her sisters and cousins');" href="#gallery"><img alt="Sarah with her sisters and cousins" src="images/gallery/familyThumbs/99958t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99959.jpg','family_','400','600','Alix and Sarah');" href="#gallery"><img alt="Alix and Sarah" src="images/gallery/familyThumbs/99959t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99960.jpg','family_','440','300','Sarah\'s sisters give her a birthday kiss');" href="#gallery"><img alt="Sarah's sisters give her a birthday kiss" src="images/gallery/familyThumbs/99960.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99961.jpg','family_','440','300','Alix, Sarah and Lilly');" href="#gallery"><img alt="Alix, Sarah and Lilly" src="images/gallery/familyThumbs/99961t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99962.jpg','family_','440','300','Dad helps Sarah talk to Grandma Esther');" href="#gallery"><img alt="Dad helps Sarah talk to Grandma Esther" src="images/gallery/familyThumbs/99962t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99964.jpg','family_','440','300','Sarah with her mom , July 4th at Lake of the Pines');" href="#gallery"><img alt="Sarah with her mom , July 4th at Lake of the Pines" src="images/gallery/familyThumbs/99964t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99965.jpg','family_','440','300','Sarah and Lilly looking over the edge');" href="#gallery"><img alt="Sarah and Lilly looking over the edge" src="images/gallery/familyThumbs/99965t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99966.jpg','family_','400','600','Grandma and Grandpa');" href="#gallery"><img alt="Grandma and Grandpa" src="images/gallery/familyThumbs/99966.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99967.jpg','family_','440','300','Sarah with her sisters, cousins and Grandparents');" href="#gallery"><img alt="Sarah with her sisters, cousins and Grandparents" src="images/gallery/familyThumbs/99967t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99968.jpg','family_','440','300','Sarah with her Grandparents');" href="#gallery"><img alt="Sarah with her Grandparents" src="images/gallery/familyThumbs/99968t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99969.jpg','family_','400','600','Alix and Lilly, Halloween');" href="#gallery"><img alt="Alix and Lilly, Halloween" src="images/gallery/familyThumbs/99969t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99970.jpg','family_','440','300','Red Tie family gathering');" href="#gallery"><img alt="Red Tie family gathering" src="images/gallery/familyThumbs/99970.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99971.jpg','family_','440','300','Sarah\'s Mom and Dad');" href="#gallery"><img alt="Sarah's Mom and Dad" src="images/gallery/familyThumbs/99971.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99972.jpg','family_','440','300','Sarah\'s Mom and Dad');" href="#gallery"><img alt="Sarah's Mom and Dad" src="images/gallery/familyThumbs/99972.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99973.jpg','family_','440','300','Sarah\'s Mom and Dad');" href="#gallery"><img alt="Sarah's Mom and Dad" src="images/gallery/familyThumbs/99973.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99974.jpg','family_','400','600','Alexandra - Photo by Leslie Corrado');" href="#gallery"><img alt="Alexandra - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99974.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99975.jpg','family_','400','600','Alexandra - Photo by Leslie Corrado');" href="#gallery"><img alt="Alexandra - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99975.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99976.jpg','family_','400','600','Mom and Lilly at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Mom and Lilly at Baker Beach - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99976.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99977.jpg','family_','400','600','Alexandra and Lilly at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Alexandra and Lilly at Baker Beach - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99977.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99978.jpg','family_','400','600','Alexandra at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Alexandra at Baker Beach - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99978t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99979.jpg','family_','400','600','Lilly at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Lilly at Baker Beach - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99979t.jpg" height="40" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99980.jpg','family_','400','600','Lilly at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Lilly at Baker Beach - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99980t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99981.jpg','family_','400','600','Mom and Alexandra at Baker Beach - Photo by Leslie Corrado');" href="#gallery"><img alt="Mom and Alexandra at Baker Beach - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99981t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99982.jpg','family_','400','600','Dad and Alexandra');" href="#gallery"><img alt="Dad and Alexandra" src="images/gallery/familyThumbs/99982t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99983.jpg','family_','440','300','Family at Christmas');" href="#gallery"><img alt="Family at Christmas" src="images/gallery/familyThumbs/99983t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99984.jpg','family_','400','600','Mom and Lilly - Photo by Leslie Corrado');" href="#gallery"><img alt="Mom and Lilly - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99984t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99985.jpg','family_','440','300','Lilly - Photo by Leslie Corrado');" href="#gallery"><img alt="Lilly - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99985t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99986.jpg','family_','440','300','Mom and the girls - Photo by Leslie Corrado');" href="#gallery"><img alt="Mom and the girls - Photo by Leslie Corrado" src="images/gallery/familyThumbs/99986t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99987.jpg','family_','400','600','Alexandra - Halloween');" href="#gallery"><img alt="Alexandra - Halloween" src="images/gallery/familyThumbs/99987t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99988.jpg','family_','400','600','Family - Summer');" href="#gallery"><img alt="Family - Summer" src="images/gallery/familyThumbs/99988t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99989.jpg','family_','440','300','Dad and Alexandra - Christmas');" href="#gallery"><img alt="Dad and Alexandra - Christmas" src="images/gallery/familyThumbs/99989t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99990.jpg','family_','440','300','Grandpa, Alexandra and John');" href="#gallery"><img alt="Grandpa, Alexandra and John" src="images/gallery/familyThumbs/99990t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99991.jpg','family_','440','300','Grandpa, Alexandra and John');" href="#gallery"><img alt="Grandpa, Alexandra and John" src="images/gallery/familyThumbs/99991t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99992.jpg','family_','440','300','Grandpa, Alexandra and John');" href="#gallery"><img alt="Grandpa, Alexandra and John" src="images/gallery/familyThumbs/99992t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99993.jpg','family_','440','300','4th of July');" href="#gallery"><img alt="4th of July" src="images/gallery/familyThumbs/99993t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99994.jpg','family_','440','300','Lilly');" href="#gallery"><img alt="Lilly" src="images/gallery/familyThumbs/99994t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99995.jpg','family_','400','600','Lilly\'s Baby Blessing');" href="#gallery"><img alt="Lilly's Baby Blessing" src="images/gallery/familyThumbs/99995t.jpg" height="41" width="27"></a>
                     <a onclick="updateImg('images/gallery/family/99996.jpg','family_','440','300','Alexandra and Lilly');" href="#gallery"><img alt="Alexandra and Lilly" src="images/gallery/familyThumbs/99996t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99997.jpg','family_','440','300','Sarah\'s maternal grandparents');" href="#gallery"><img alt="Sarah's maternal grandparents" src="images/gallery/familyThumbs/99997t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99998.jpg','family_','440','300','Lilly');" href="#gallery"><img alt="Lilly" src="images/gallery/familyThumbs/99998t.jpg" height="27" width="40"></a>
                     <a onclick="updateImg('images/gallery/family/99999.jpg','family_','1','1','');" href="#gallery"><img alt="" src="images/gallery/familyThumbs/99999t.jpg" height="1" width="1"></a></div>
               </div>
            </div>
<?php require_once( 'footerInc.php' ); ?>
