<?php
$pgId = "rose";
require_once( 'headerInc.php' );
require_once( 'navInc.php' );
?>
               <div id="mainContent">
                  <h3>Is Rett Syndrome the Rosetta Stone of Neurologic Diseases?</h3>
                  <p>Rett Syndrome (RS), a neurological orphan disease of children that was long relegated to obscure articles and the fervent concern of parents, might soon be adopted into a family of higher-profile neurologic disorders. This change from medical oddity to the focus of avid researchers reflects the exciting discovery of genetic similarities between RS and disorders as disparate as autism and Alzheimer disease. And if this early promise holds true, RS will no longer be a medical trivia question. Rather, it could become a medical Rosetta Stone for translating a tangle of genetic and biochemical evidence into a real understanding of some terrible neurological conditions.</p>
                  <p>That ancient slab of writing, found in the Nile delta area in 1799, was inscribed in multiple languages &mdash; Egyptian hieroglyphics, a simpler form of Egyptian writing, and Greek. By comparing how the same messages were written in these different languages, a French scholar was able to decode the language of hieroglyphics by 1822. This monumental breakthrough in understanding an important age in ancient history occurred because the Rosetta stone shed light on the similarities between known and unknown languages. Likewise, medical scholars are now decoding the mysteries of certain brain disorders by comparing them to RS.</p>
                  <p>RS seems to be a classic example of a "chromatin disease," a general term for a specific mutation that cripples the ability of cells to control the activity of a variety of genes.</p>
                  <p>Chromatin is the "storage" form of DNA inside the nucleus of a cell. This highly condensed form of DNA lets the enormous lengths of chromosomes remain tightly packed; but it permits specific genes to be accessed and activated when the cell needs them to perform their assigned tasks.</p>
                  <p>In chromatin, the long chains of DNA making up the chromosomes are wrapped around proteins called histones. This reduces the space the DNA takes up, while leaving genes available for duty in the cell. This is like a twenty-foot length of thread being wrapped around a spool, greatly reducing the space it takes up, even while leaving it available to make or repair clothes. (In the case of histones, however, the continuous length of DNA is wrapped around a series of histone proteins rather than around just one; this keeps DNA from being bunched up on a single "spool" and allows access to many genes at once.)</p>
                  <p>Chromatin diseases are attracting increased attention because of their direct link to a variety of disorders, ranging from mental illness to cancer. And RS stands at the center of the growing excitement over chromatin diseases. As investigators peel away the layers of molecular mysteries around RS, they are uncovering evidence that may help them treat other neurologic diseases.</p>
                  <p>Indeed, investigators are now hot on the trail of a cure for the blood cancer promyelocytic leukemia, based on their understanding of chromatin diseases.</p>
<?php require_once( 'footerInc.php' ); ?>
